### ISSUE TITLE
Bug in AdvanceNext if next scheduled time is 0

### ISSUE THREAD

**Issue by oliverdain** [coder/quartz#11]
The following unit test fails with a panic:

```go
func TestQuartz(t *testing.T) {
	clock := quartz.NewMock(t)
	doneChan := make(chan any)
	go func() {
		timer := clock.NewTimer(0 * time.Second)
		<- timer.C
		close(doneChan)
	}()
	newTimerTrap := clock.Trap().NewTimer()
	defer newTimerTrap.Close()
	clock.AdvanceNext()
	<- doneChan
	log.Infof("Done at %s", clock.Now().String())
}
```

The issue is that I'm setting a timer with duration 0 which is legal. However, if you look at `AdvanceNext` you see:

```go
func (m *Mock) AdvanceNext() (time.Duration, AdvanceWaiter) {
	m.mu.Lock()
	m.tb.Helper()
	w := AdvanceWaiter{tb: m.tb, ch: make(chan struct{})}
	if m.nextTime.IsZero() {
		defer close(w.ch)
		defer m.mu.Unlock()
		m.tb.Error("cannot AdvanceNext because there are no timers or tickers running")
	}
	d := m.nextTime.Sub(m.cur)
	m.cur = m.nextTime
	go m.advanceLocked(w)
	return d, w
}
```

There's two bugs here I think:

1. It checks if `m.nextTime.IsZero` but that doesn't necessarily mean there's nothing scheduled as it is legal to set a timer with a duration of 0
2. If it does hit that condition it calls `defer m.mu.Unlock` but then it still calls `advanceLocked`  which unlocks that mutex so you get a panic due to a double unlock of the mutex.

Granted it's a bit of an odd case to schedule a timer for 0 seconds in the future but I think there are valid use cases for it. For my use case a user puts a request for a function to be called into a channel. We read from that channel and schedule the callback. It is possible that by the time we read from the channel the time has expired so we should call right away. We could special case that code but as it's legal to schedule a timer with 0-delay with a real timer and that's less code and fewere if statements we simply schedule the timer to fire immediately.

**Comment by spikecurtis** [comment]
The issue of the double-unlock is a legit bug and was fixed in: https://github.com/coder/quartz/pull/10.

Zero-duration timers _are_ fine in Quartz, but they fire immediately: https://github.com/coder/quartz/blob/d4dbd838d0902c80470febbeee0442814c7bc490/mock.go#L91

So, it is _not fine_ to call `AdvanceNext()` after because there is nothing else scheduled.

Also, as an aside, in your example, I see that you set a trap for `NewTimer()`.

1. The trap is set _after_ you start a go routine that calls `NewTimer()`. This will race and there is no guarantee that you will actually trap the call. You need to set the trap before you start the goroutine.
2. Your code never calls `Wait()` on the trap. After setting the trap, you need to `Wait()` on it and then `Release()` the call in order for `NewTimer()` to return.

Closing because I think the actual bug is already resolved. Please reopen if you think there is still an issue with the latest `main` branch.

**Comment by oliverdain** [comment]
Thanks for the prompt reply! You're correct about the `NewTimer` trap - that was left over from the "real unit test" that was failing when I simplified it to make it suitable for a bug report.

It does look like the bug is fixed on `main` but that hasn't been released. The latest release, the one `go mod tidy` pulls, is 0.1.2 which was released before the bug fix. Any chance you could push a new release with the fix?

**Comment by spikecurtis** [comment]
New release published!
